/* do not change this file, it is auto generated by storybook. */
/// <reference types="@storybook/react-native/metro-env" />
import { start, updateView, View, type Features } from "@storybook/react-native";

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-backgrounds/register";
import "@storybook/addon-ondevice-notes/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../components",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.\.\/components(\/.*)?\/[^/]*\.stories\.(ts|tsx|js|jsx)$/,
    req: require.context("../components", true, /\.stories\.(ts|tsx|js|jsx)$/),
  },
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var FEATURES: Features;
}

const annotations = [
  require("@storybook/react-native/preview"),
  require("./preview"),
];

globalThis.STORIES = normalizedStories;

module?.hot?.accept?.();

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
