/* eslint-disable */
// This file is auto-generated by Storybook's metro plugin.
// Re-run `npx expo start` to regenerate after adding new stories.

import { configure } from "@storybook/react-native";

configure(() => {
  require("../components/ui/Button.stories");
  require("../components/ui/Card.stories");
  require("../components/ui/ProgressBar.stories");
  require("../components/ui/EmptyState.stories");
  require("../components/ui/Divider.stories");
  require("../components/budget/CategoryCard.stories");
  require("../components/budget/BudgetAlertBanner.stories");
  require("../components/dashboard/TransactionItem.stories");
}, module);
